module.exports = {
  extends: ["@commitlint/config-conventional"],
  ignores: [(msg) => /Signed-off-by: dependabot\[bot\]/.test(msg)],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "perf",
        "refactor",
        "test",
        "docs",
        "build",
        "ci",
        "chore",
        "style",
        "revert",
        "deps",
        "sec",
      ],
    ],
    "scope-enum": [
      1,
      "always",
      [
        "api",
        "worker",
        "frontend",
        "backend",
        "queue",
        "domain",
        "infra",
        "ci",
        "deps",
        "docs",
        "readme",
        "github",
        "landing",
        "docker",
      ],
    ],
    "subject-case": [2, "never", ["upper-case", "pascal-case", "start-case"]],
    "header-max-length": [2, "always", 200],
    "body-max-line-length": [0],
  },
};
